import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/AddDownloadModal.svelte', import.meta.url), 'utf8');
const styles = await readFile(new URL('../src/app.css', import.meta.url), 'utf8');

assert.match(source, /bg-background\/60 p-4 backdrop-blur-\[1px\]/, 'modal backdrop should keep the Svelte translucent background and blur');
assert.match(source, /w-full max-w-xl[\s\S]*rounded-md[\s\S]*bg-card[\s\S]*animate-in fade-in zoom-in-95/, 'modal shell should keep the Svelte width, radius, card surface, and entrance animation');
assert.match(source, /New Download/, 'modal title should match the Svelte capitalization');
assert.match(source, /Add a file, torrent, or bulk links\./, 'modal subtitle should match the Svelte copy');
assert.match(source, /Close new download/, 'close button should keep the Svelte accessible label');
assert.match(source, /import \{ tick \} from 'svelte'/, 'modal should import tick so the loading buffer can render before submit work begins');
assert.match(source, /grid grid-cols-3 rounded-md border border-border bg-background p-1/, 'download mode tabs should use the compact Svelte segmented control');
for (const label of ['File', 'Torrent', 'Bulk']) {
  assert.match(source, new RegExp(`label: '${label}'`), `download mode label ${label} should match Svelte`);
}
assert.doesNotMatch(source, /label: 'Multi'|mode === 'multi'|multiUrls|multi-download-urls/, 'multi-download mode should not be exposed in the add-download modal');
assert.match(source, /browseTorrentFile/, 'torrent mode should wire the Import button to the native torrent import picker');
assert.match(source, /PackagePlus[\s\S]*Import/, 'torrent mode should render a compact Import button with an icon');
assert.match(source, /event\.target === event\.currentTarget/, 'the modal should only close when the backdrop itself is clicked');
assert.match(source, /event\.key === 'Escape'/, 'the modal should close when Escape is pressed');
assert.match(source, /document\.addEventListener\('keydown', closeOnEscape\)/, 'the modal should register a document Escape listener while open');
assert.match(source, /document\.removeEventListener\('keydown', closeOnEscape\)/, 'the modal should remove its Escape listener on unmount');
assert.match(source, /progressPopupIntentForSubmission/, 'added downloads should still return the popup intent used by the app shell');
assert.match(source, /mode === 'torrent'[\s\S]*transferKind: 'torrent'/, 'torrent submissions should keep the torrent transfer kind');
assert.match(source, /defaultBulkOutputNameForUrls/, 'bulk folder names should be suggested from pasted multipart links');
assert.doesNotMatch(source, /bulkOutputKind/, 'bulk modal should not expose an archive-or-folder output kind');
assert.match(source, /let archiveName = \$state\('bulk-download'\)/, 'bulk combine should default to a folder-safe output name');
assert.doesNotMatch(source, /let bulkOutputKind = \$state<BulkOutputKind>/, 'bulk combine should not keep a selectable output-kind state');
assert.doesNotMatch(source, /<span>Archive<\/span>/, 'bulk modal should not offer Archive output choices');
assert.doesNotMatch(source, /<span>Folder<\/span>/, 'bulk modal should not show a folder output choice or badge');
assert.doesNotMatch(source, /FolderOpen/, 'bulk modal should not use folder-specific chrome for the combine control');
assert.doesNotMatch(source, /setBulkOutputKind/, 'bulk modal should not include archive/folder switching code');
assert.match(source, /File Combine/, 'bulk combine label should use the concise File Combine wording');
assert.match(source, /<span class="min-w-0 whitespace-nowrap">File Combine<\/span>/, 'bulk combine label should stay on one line in the compact label column');
assert.doesNotMatch(source, /Combine downloads/, 'bulk combine should not use the old Combine downloads label');
assert.match(source, /title="Keep completed files together\."/, 'bulk combine helper copy should live in a hover tooltip instead of visible helper text');
assert.doesNotMatch(source, /Save as one archive or folder\./, 'bulk combine should not mention archive output');
assert.match(source, /space-y-3 rounded-md border border-border bg-background px-3 py-4/, 'bulk combine panel should stack its controls so the name input can own a full row');
assert.match(source, /<div class="flex items-center gap-3">[\s\S]*File Combine[\s\S]*<\/label>\s*<\/div>/, 'bulk combine header should contain only the checkbox label without output-kind chrome');
assert.match(source, /<\/div>\s*<input class="h-10 w-full rounded-md border border-input bg-card px-3 text-sm text-foreground outline-none transition focus:border-primary disabled:cursor-not-allowed disabled:opacity-50"[\s\S]*aria-label="Bulk output name" \/>/, 'bulk output name input should be a full-width row under the File Combine header');
assert.doesNotMatch(source, /md:grid-cols-\[minmax\(0,140px\)_minmax\(0,1fr\)\]/, 'bulk combine panel should not keep the old two-column grid layout');
assert.doesNotMatch(source, /md:grid-cols-\[170px_minmax\(0,1fr\)\]/, 'bulk output controls should not reserve a fixed grid column before the name input');
assert.match(source, /archiveNameTouched/, 'manual bulk archive names should not be overwritten by later pasted links');
assert.match(source, /bulkStartBehavior/, 'bulk submissions should read the configured start behavior');
assert.match(source, /addJobs\(urls, trimmedArchiveName, \{ resolveHosterLinks: true, startPaused: bulkStartBehavior !== 'start_immediately' \}\)/, 'bulk submissions should resolve hoster links and use the configured review/start behavior without an archive option');
assert.match(source, /Resolving links\.\.\./, 'bulk submissions should show resolver-specific wait feedback while hoster links are being prepared');
assert.match(source, /isSubmitting = true;[\s\S]*submitStatusLabel = mode === 'bulk' \? 'Resolving links\.\.\.' : 'Adding\.\.\.';[\s\S]*await tick\(\);[\s\S]*try \{/, 'submit should yield after setting the loading state so the buffer can paint before backend work starts');
assert.doesNotMatch(source, /rounded-md border border-border bg-background px-3 py-2 text-xs text-muted-foreground[\s\S]*<span>\{readyLabel\}<\/span>/, 'the standalone ready summary box should be removed');
assert.doesNotMatch(source, /Queue only/, 'single-file mode should not show the old Queue only summary text');
assert.match(source, /\{#if isSubmitting\}[\s\S]*animate-\[download-buffer_1\.1s_ease-in-out_infinite\][\s\S]*\{\/if\}[\s\S]*<footer/, 'submitting should show a thin indeterminate buffer above the footer');
assert.match(styles, /@keyframes download-buffer[\s\S]*translateX\(-100%\)[\s\S]*translateX\(300%\)/, 'download buffer animation should define the indeterminate keyframes used by the modal');
assert.match(source, /<footer class="flex items-center justify-between gap-3 border-t border-border px-5 py-3">[\s\S]*\{#if mode === 'bulk'\}[\s\S]*<span class="text-xs font-semibold text-primary">\{readyLabel\}<\/span>[\s\S]*\{:else if mode === 'torrent'\}/, 'footer should show the accent ready label only for bulk mode and keep torrent import in the left slot');
