import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/App.svelte', import.meta.url), 'utf8');

assert.match(source, /isDownloadSectionExpanded/, 'the regular download sidebar section should track expanded/collapsed state');
assert.match(source, /isBulkSectionExpanded/, 'the bulk sidebar section should track expanded/collapsed state');
assert.match(source, /isTorrentSectionExpanded/, 'the torrent sidebar section should track expanded/collapsed state');
assert.match(source, /Collapse downloads section/, 'the all-downloads section should expose an accessible collapse action');
assert.match(source, /Collapse bulk downloads section/, 'the bulk-downloads section should expose an accessible collapse action');
assert.match(source, /Collapse torrents section/, 'the torrent section should expose an accessible collapse action');
assert.match(source, /isBulkStatusView \? 'bulk' : isTorrentStatusView \? 'torrents' : 'downloads'/, 'the footer status bar should switch to bulk and torrent-specific modes');
assert.match(source, /Download size=\{16\} class="text-primary"[\s\S]*formatBytes\(torrentStats\.downloadedBytes\)[\s\S]*Total Ratio/, 'the torrent footer should show total torrent downloaded bytes before total ratio');
assert.match(source, /download-sidebar flex w-\[220px\] shrink-0 flex-col overflow-hidden/, 'the sidebar shell should constrain overflow so only the navigation section scrolls');
assert.match(source, /<nav class="min-h-0 flex-1 overflow-y-auto overscroll-contain/, 'the sidebar navigation should scroll independently on short windows');
assert.match(source, /Gauge, 'Active'[\s\S]*CheckCircle2, 'Completed'[\s\S]*Bulk Downloads[\s\S]*Torrents/, 'Bulk downloads should have their own sidebar section between completed downloads and torrents');
assert.match(source, /class="shrink-0 space-y-2"/, 'the Settings footer should stay fixed below the scrollable sidebar navigation');
assert.match(source, /import \{ SETTINGS_SECTIONS, type SettingsSectionId \} from '\.\/settingsSections'/, 'the app shell should consume the shared settings section list');
assert.doesNotMatch(source, /^import\s+.*\.\/SettingsPage\.svelte/m, 'the app shell should lazy-load the heavy settings page component');
assert.match(source, /let activeSettingsSectionId = \$state<SettingsSectionId>\(SETTINGS_SECTIONS\[0\]\.id\)/, 'settings view should track the active settings section');
assert.match(source, /SettingsSidebar\(activeSettingsSectionId/, 'settings view should keep the Svelte settings sidebar outside the settings form');
assert.match(source, /Back to downloads/, 'settings sidebar should expose the Svelte back action');
assert.match(source, /shrink-0 space-y-2 border-b border-border\/35 pb-2/, 'settings sidebar header divider should use the softened settings separator');
assert.match(source, /function handleSettingsSectionClick\(sectionId: SettingsSectionId\)[\s\S]*activeSettingsSectionId = section\.id/, 'settings sidebar should update the active section from the shell');
assert.match(source, /SettingsSidebar\(activeSettingsSectionId[\s\S]*handleSettingsSectionClick/, 'settings sidebar section clicks should go through the guarded section-navigation helper');
assert.match(source, /function handleSettingsSectionClick\(sectionId: SettingsSectionId\)[\s\S]*window\.history\.replaceState\(null, '', section\.href\)[\s\S]*settingsScrollRoot[\s\S]*querySelector<HTMLElement>\(section\.href\)[\s\S]*scrollRoot\.scrollTo/, 'settings section navigation should update the hash and scroll only the settings pane');
assert.match(source, /function handleSettingsSectionClick\(sectionId: SettingsSectionId\)[\s\S]*window\.scrollTo\(\{ top: 0, left: 0, behavior: 'auto' \}\)/, 'settings section navigation should keep the app titlebar pinned after hash updates');
assert.doesNotMatch(source, /scrollIntoView\(\{ block: 'start' \}\)/, 'settings section navigation should not use document-level scrollIntoView');
assert.match(source, /onclick=\{\(event\) => \{[\s\S]*event\.preventDefault\(\)[\s\S]*onSettingsSectionClick\(section\.id\)/, 'settings sidebar anchors should prevent default browser hash scrolling so the titlebar remains visible');
assert.match(source, /bind:this=\{settingsScrollRoot\}/, 'settings page should live inside the scroll root used for active-section tracking');
assert.match(source, /new IntersectionObserver/, 'settings active section should still update from scroll position');
assert.match(source, /onCancel=\{\(\) => requestViewChange\('all'\)\}/, 'settings page cancel should leave through the app dirty-state guard');
assert.doesNotMatch(source, /Needs Attention|label="Queued"|return '(?:attention|queued|torrent-attention|torrent-queued)'/, 'the sidebar should not render removed attention or queued filters');
assert.doesNotMatch(source, /setView\(outcome\.mode === 'torrent' \? 'torrent-queued' : 'queued'\)|setView\('queued'\)/, 'new downloads should not navigate to removed queued-only views');
