import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const appSource = readFileSync(new URL('../src/App.svelte', import.meta.url), 'utf8');
const backendSource = readFileSync(new URL('../src/backend.ts', import.meta.url), 'utf8');
const backendPreviewSource = readFileSync(new URL('../src/backendPreview.ts', import.meta.url), 'utf8');
const queueSource = readFileSync(new URL('../src/QueueView.svelte', import.meta.url), 'utf8');
const batchSource = readFileSync(new URL('../src/BatchProgressWindow.svelte', import.meta.url), 'utf8');

assert.match(appSource, /groupBulkQueueRows\(jobs\)/, 'App should group bulk members before queue counts, filtering, sorting, and rendering');
assert.match(appSource, /openBatchProgressWindow\(\{[\s\S]*kind: 'bulk'[\s\S]*bulkMemberIds/, 'bulk aggregate Show Popup should open the batch progress popup for all member jobs');
assert.match(backendSource, /export async function openBulkArchive\(archiveId: string\)/, 'backend should expose an archive-level open wrapper');
assert.match(backendSource, /export async function revealBulkArchive\(archiveId: string\)/, 'backend should expose an archive-level reveal wrapper');
assert.match(queueSource, /function bulkOpenLabel[\s\S]*Open Folder[\s\S]*Open File/, 'completed bulk aggregate menus should label folder outputs as Open Folder and archives as Open File');
assert.doesNotMatch(batchSource, /Reveal completed/, 'bulk progress popup should not expose the old Reveal completed action');
assert.match(batchSource, /Uncompressing/, 'bulk progress popup should show uncompressing as a distinct finalizing phase');
assert.match(batchSource, /Combining/, 'bulk progress popup should show combining as a distinct finalizing phase');
assert.match(batchSource, /Compressing/, 'bulk archive output should show compression as a distinct finalizing phase');
assert.match(batchSource, /Review links/, 'bulk progress popup should show the pre-download review phase');
assert.match(batchSource, /deleteJobs/, 'bulk progress popup should let the initial review state cancel the queued batch');
assert.match(batchSource, /function startBulkDownload\(\)[\s\S]*resumeJobs/, 'bulk progress popup should start paused bulk jobs only after user confirmation');
assert.match(batchSource, /bulkUiState === 'review'[\s\S]*ActionButton\(isConfirmingCancel \? 'Confirm' : 'Cancel'[\s\S]*ActionButton\('Start'/, 'review footer should expose only two-step Cancel and Start before active controls');
assert.doesNotMatch(batchSource, /isBulkReviewPhase[\s\S]{0,260}Pause all/, 'review footer should not show Pause all');
assert.doesNotMatch(batchSource, /isBulkReviewPhase[\s\S]{0,260}Resume all/, 'review footer should not show Resume all');
assert.doesNotMatch(batchSource, /isBulkReviewPhase[\s\S]{0,260}Cancel active/, 'review footer should not show Cancel active');
assert.match(batchSource, /archive\?\.warning/, 'bulk progress popup should surface cleanup warnings after a completed archive');
assert.doesNotMatch(batchSource, /summary\.activeCount === 0[\s\S]{0,240}Pause all/, 'inactive batch popup footer should not keep disabled pause controls visible');
assert.match(batchSource, /selectedBulkJobIds/, 'bulk review rows should track local checked include state');
assert.match(batchSource, /type="checkbox"/, 'bulk review rows should expose per-file include checkboxes');
assert.match(batchSource, /bulkHasStarted/, 'bulk popup should keep local started state after the user clicks Start');
assert.match(batchSource, /isUntouchedBulkReviewGate/, 'bulk popup should derive the first review gate from untouched pending jobs');
assert.match(batchSource, /bulkReviewStartSelection/, 'bulk Start should partition included and excluded review rows');
assert.match(batchSource, /deleteJobs\(selection\.excludedJobs\.map\(\(job\) => job\.id\), false\)/, 'bulk Start should remove unchecked review rows without deleting files from disk');
assert.doesNotMatch(batchSource, /bulkUiState === 'review'[\s\S]{0,280}Resume/, 'bulk review footer should say Start, not Resume');
assert.match(batchSource, /isConfirmingCancel/, 'bulk Cancel should use the same two-step confirmation transition as other progress popups');
assert.match(batchSource, /bulkUiState === 'finalizing'[\s\S]*BulkFinalizingStrip/, 'bulk finalizing state should render the adaptive no-action phase strip');
assert.doesNotMatch(batchSource, /bulkUiState === 'finalizing'[\s\S]{0,360}ActionButton/, 'bulk finalizing state should not render footer actions');
assert.doesNotMatch(batchSource, /ActionButton\(bulkOpenLabel\(completedArchive\)/, 'ready bulk popup should expose only Show, not a second Open action');
assert.match(backendPreviewSource, /width=640,height=480/, 'browser fallback batch progress popup should use the redesigned 640x480 size');
