import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const progressSource = readFileSync(new URL('../src/DownloadProgressWindow.svelte', import.meta.url), 'utf8');
const sharedPopupSource = readFileSync(new URL('../src/useProgressPopup.svelte.ts', import.meta.url), 'utf8');
const backendPreviewSource = readFileSync(new URL('../src/backendPreview.ts', import.meta.url), 'utf8');
const windowsSource = readFileSync(new URL('../src-tauri/src/windows.rs', import.meta.url), 'utf8');

assert.match(progressSource, /@render ProgressView\(/, 'download progress controller should render the compact progress view');
assert.match(progressSource, /#snippet ProgressView/, 'normal downloads should render through a named compact progress view');
assert.doesNotMatch(progressSource, /TorrentingProgressView|Torrent session|Uploaded|Ratio/, 'normal download progress popup should not include torrent-specific UI');
assert.match(progressSource, /PopupTitlebar title="Download progress"/, 'normal progress popup should keep the Download progress title');
assert.match(progressSource, /Metric\('Speed'[\s\S]*Metric\('ETA'[\s\S]*Metric\('Size'/, 'compact download view should keep speed, ETA, and size metrics visible in a flat metric rail');
assert.doesNotMatch(progressSource, /function MetricGrid|rounded border border-border bg-background/, 'progress popup metrics should be flat instead of boxed cards');
assert.match(progressSource, /grid grid-cols-3 gap-2 border-t border-border\/35 bg-background\/30/, 'progress popup metric rail should use softer boxed-in shading and a muted top separator');
assert.match(progressSource, /function isActiveProgressJob\(job: DownloadJob\)[\s\S]*JobState\.Queued[\s\S]*JobState\.Starting[\s\S]*JobState\.Downloading/, 'download progress popup should identify queued, starting, and downloading as active transfer states');
assert.match(progressSource, /#if isActiveProgressJob\(job\)[\s\S]*Action\('Pause'[\s\S]*Action\(isConfirmingCancel \? 'Confirm' : 'Cancel'[\s\S]*#if job\.state === JobState\.Paused/, 'active download progress should expose only Pause and Cancel controls');
assert.match(progressSource, /#if job\.state === JobState\.Paused[\s\S]*Action\('Resume'[\s\S]*Action\(isConfirmingCancel \? 'Confirm' : 'Cancel'[\s\S]*#if job\.state === JobState\.Failed/, 'paused download progress should expose only Resume and Cancel controls');
assert.match(progressSource, /#if job\.state === JobState\.Completed[\s\S]*Action\('Show'[\s\S]*revealJobInFolder\(job\.id\);[\s\S]*\{ closeOnSuccess: true \}[\s\S]*Action\('Open'[\s\S]*openJobFile\(job\.id\);[\s\S]*\{ closeOnSuccess: true \}/, 'completed download progress should expose Show and Open, both closing the popup after success');
assert.doesNotMatch(progressSource, /Action\('Reveal'/, 'normal download progress popup should label completed reveal as Show, not Reveal');
assert.match(progressSource, /job\.state === JobState\.Canceled[\s\S]*Action\('Close'/, 'canceled download progress should expose a safe Close fallback');
assert.match(progressSource, /Action\('Open'[\s\S]*openJobFile\(job\.id\);[\s\S]*\{ closeOnSuccess: true \}/, 'completed download Open should close the popup after a successful action');
assert.match(sharedPopupSource, /cancelJob\(activeJobId\)[\s\S]*closeOnSuccess:\s*true/, 'confirmed progress Cancel should close the popup after successful cancellation');
assert.match(progressSource, /type ActionVariant = 'default' \| 'primary' \| 'cancel' \| 'confirm'/, 'download progress actions should use explicit variants for cancel confirmation states');
assert.match(progressSource, /isConfirmingCancel \? 'confirm' : 'cancel'/, 'download progress cancel button should switch to a confirm variant on the second click');
assert.match(progressSource, /case 'cancel':[\s\S]*border-destructive bg-destructive text-destructive-foreground[\s\S]*cursor-pointer/, 'download progress Cancel should be a red button with white text and an action cursor');
assert.match(progressSource, /case 'confirm':[\s\S]*border-border bg-white text-black[\s\S]*cursor-pointer/, 'download progress Confirm should be a white button with black text and an action cursor');
assert.match(progressSource, /disabled:cursor-not-allowed/, 'download progress action buttons should show a disabled cursor while busy');
assert.match(windowsSource, /width:\s*460\.0,[\s\S]*height:\s*280\.0,/, 'download progress popup geometry should stay compact for normal downloads');
assert.match(backendPreviewSource, /width=460,height=280/, 'browser fallback download progress popup should keep the compact 460x280 geometry');
