import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const source = await readFile(new URL('../src/QueueView.svelte', import.meta.url), 'utf8');
const appSource = await readFile(new URL('../src/App.svelte', import.meta.url), 'utf8');
const fileBadgeSource = await readFile(new URL('../src/FileBadge.svelte', import.meta.url), 'utf8');

assert.match(source, /queueTableColumnsForView\(view\)/, 'queue should use the React view-specific column helper');
assert.match(source, /tableColumns\[2\] === 'Seed'/, 'torrent views should switch to the React seed and ratio columns');
assert.match(source, /getVirtualQueueWindow/, 'queue should keep the React virtualization window for large queues');
assert.match(source, /queueRowSizeClass\(queueRowSize\)/, 'queue rows should read their density from the saved queue row-size setting');
assert.match(source, /default:[\s\S]*return 'min-h-\[42px\] py-1 text-sm'/, 'medium queue row size should preserve the current default density');
assert.match(source, /case 'compact':[\s\S]*min-h-\[28px\] py-0 text-xs[\s\S]*case 'small':[\s\S]*min-h-\[34px\] py-0\.5 text-xs[\s\S]*case 'large':[\s\S]*min-h-\[54px\] py-1\.5 text-sm[\s\S]*case 'damn':[\s\S]*min-h-\[68px\] py-2\.5 text-base/, 'queue row sizing should match React density classes');
assert.match(source, /rowSize=\{queueRowSize\}/, 'queue row file badges should receive the saved queue row-size setting');
assert.match(fileBadgeSource, /function fileBadgeDensity\(rowSize: QueueRowSize/, 'file badges should keep React density sizing');
assert.match(source, /selectedJob && showDetailsOnClick/, 'selected-download details should render only when click-to-show details is enabled');
assert.match(source, /detailsHeight/, 'details pane should keep the React resizable height state');
assert.match(source, /GripHorizontal/, 'details pane should keep the React resize affordance');
assert.match(source, /ondblclick=\{\(event\) => \{[\s\S]*shouldOpenJobFileOnDoubleClick\(job, event\.button\)[\s\S]*onOpen\(job\.id\)/, 'queue row double-click should open the file instead of revealing the folder');
assert.match(source, /function toggleSingleJobSelection\(jobId: string\)/, 'queue row click should keep the React toggle selection helper');
assert.match(source, /function applySelectionRange/, 'queue should keep React drag/range selection behavior');
assert.match(source, /Open Folder[\s\S]*onReveal\(job\.id\)/, 'the context menu Open Folder action should still reveal the file location');
assert.match(source, /grid min-w-\[1080px\] grid-flow-col auto-cols-\[minmax\(260px,1fr\)\] grid-rows-2 gap-x-3 gap-y-2/, 'compact details should use self-contained scrolling detail cells with enough width for each value');
assert.match(source, /#snippet CompactDetailItem[\s\S]*class="min-w-0 px-1 py-1"/, 'compact detail items should be unframed rather than card-like boxes');
assert.doesNotMatch(source, /rounded-sm border border-border\/70 bg-background\/35 px-2\.5 py-1\.5/, 'compact detail items should not keep the previous card-style wrapper');
assert.match(source, /title=\{value\}>\{value\}/, 'compact detail values should keep the full value available as hover text while truncating visually');
assert.match(source, /openMenuJobId === job\.id[\s\S]*RowMenu\(job, 'actions'\)/, 'row action menu should render the shared row menu');
assert.match(source, /contextMenu[\s\S]*RowMenu\(job, 'context'\)/, 'right-click context menu should render the shared row menu');
assert.match(source, /canShowProgressPopup\(job\)[\s\S]*Show Popup/, 'Show Popup should be gated to active download states');
assert.match(source, /onShowPopup: \(id: string\) => void;/, 'QueueView should accept an explicit Show Popup callback');
assert.match(appSource, /async function handleShowPopup\(id: string\)[\s\S]*await openProgressWindow\(id\)/, 'App should wire Show Popup through the existing progress popup opener');
assert.match(appSource, /onShowPopup=\{\(id\) => void handleShowPopup\(id\)\}/, 'QueueView should receive the Show Popup handler from App');
